/**
 * Dell/NVIDIA blog writing rules distilled from blog-generation-tool-v2.
 * These are hard constraints enforced during draft generation and editorial passes.
 */

export const WRITING_RULES = {
	title: {
		maxWords: 9,
		guidelines: [
			"Count every word including articles (a, an, the)",
			"Hyphenated words count as single words",
			"Capture emotional hook or specific benefit",
			"Focus on customer outcome or transformation",
			"Avoid generic technology announcements",
		],
	},
	wordCount: {
		minimum: 600,
		optimalMin: 600,
		optimalMax: 750,
		justificationRequired: 750,
		hardMax: 900,
	},
	quotes: {
		maxTotal: 5,
		guidelines: [
			"Choose quotes that advance the story or reveal character",
			"Let the narrative breathe between quotes",
			"Clean up disfluencies while preserving authentic voice",
			"Never use say-then-quote antipattern (e.g. 'John said: ...')",
		],
	},
	apStyle: [
		"Numerals for 10 and above, spell out one through nine",
		"Active voice and strong verbs throughout",
		"Serial commas consistently",
		"Short words, short sentences, short paragraphs",
		"Subject-Verb-Object structure",
		"No em dashes — use regular dashes or restructure",
		"No double negatives",
		"American English conventions",
	],
	techSpecificity: {
		defaults: ["Dell workstation", "NVIDIA accelerated computing"],
		allowGranular:
			"Only when specs directly demonstrate workflow gains, create dramatic tension, or illustrate time savings",
	},
	structure: {
		format: "5-section business blog",
		sections: {
			introduction: { words: "75-150", paragraphs: "1-2" },
			problemIdentification: { words: "125-200" },
			solution: { words: "200-350" },
			conclusion: { words: "75-175" },
		},
		priorities: [
			"Conciseness over elaborate storytelling",
			"Business value over technical specifications",
			"Problem-solution clarity over narrative complexity",
		],
	},
	cta: {
		dellFocus:
			"Discover how Dell Pro Max workstations can transform your creative workflow",
		nvidiaFocus: "Explore NVIDIA RTX solutions for accelerated computing",
		combined:
			"Learn more about Dell and NVIDIA solutions powering creative professionals",
		placement: "After main content conclusion, integrated with story resolution",
	},
} as const;

export const BANNED_WORDS: string[] = [
	"crucial",
	"ensuring",
	"critical",
	"optimized",
	"intensive",
	"featuring",
	"dramatically",
	"powerful",
	"groundbreaking",
	"robust",
	"key",
	"enhanced",
	"suddenly",
	"cutting-edge",
	"state-of-the-art",
	"next-generation",
	"unparalleled",
	"leading-edge",
	"best-in-class",
	"industry-leading",
	"world-class",
	"synergy",
	"leverage",
	"solution",
	"ecosystem",
	"game-changing",
	"pioneering",
	"visionary",
	"transformative",
	"transformed",
	"revolutionizing",
	"seamlessly",
	"partnership",
	"innovation",
	"reconceptualize",
	"demassification",
	"attitudinally",
	"judgmentally",
	"utilization",
	"ameliorate",
	"facilitate",
	"synergize",
	"paradigm",
	"optimize",
	"streamline",
	"innovate",
	"transform",
	"revolutionize",
];

export const BANNED_PHRASES: string[] = [
	"In conclusion",
	"To summarize",
	"As mentioned earlier",
	"As previously stated",
	"It is important to note that",
	"Keep in mind that",
	"One of the main advantages is",
	"One key aspect is",
	"This process can be broken down into steps",
	"This brings us to",
	"Moving forward, let's discuss",
	"Broadly speaking",
	"To better understand",
	"To put it simply",
	"A comprehensive approach",
	"A holistic view",
	"The key takeaway is",
	"It's not X—it's about Y",
	"From the X to the Y",
	"More than just X—they Y",
	"At the forefront of this change",
	"Particularly those in X",
	"for work on the go",
	"In today's rapidly evolving technological landscape",
	"Imagine this",
	"picture this",
	"get this",
	"In today's digital landscape",
	"The result speaks for itself",
	"enters the picture",
	"The screen flickered to life",
	"In the beginning",
	"Picture this",
	"Once upon a time",
	"The future of",
	"Welcome to the world of",
	"In a world where",
	"In this age of",
	"had no idea what was coming",
];
